"""Stable public contracts for deterministic research."""

from quantos.contracts.backtest import (
    BacktestArtifactFile,
    BacktestArtifactManifest,
    BacktestInputHash,
    BacktestReconciliation,
    BacktestReconciliationCheck,
    QlibBacktestConfig,
)
from quantos.contracts.base import (
    CanonicalContract,
    CanonicalizationError,
    canonical_json_bytes,
    sha256_bytes,
)
from quantos.contracts.cost import BacktestPolicy, CostPolicy
from quantos.contracts.events import EventType, ImmutableEvent
from quantos.contracts.pit import (
    CanonicalPITAuditRequest,
    LineageSource,
    MembershipUse,
    OperatorDelayPolicy,
    PITAuditReport,
    PITAuditSpec,
    PITEvidenceMode,
    PITGateId,
    PITGateResult,
    SafeExpressionNode,
    SafeQlibExpressionSpec,
    SafeQlibOperator,
    TransformLineage,
)
from quantos.contracts.provenance import CodeProvenance, RuntimeFingerprint, RuntimePackageVersion
from quantos.contracts.qlib_view import (
    ConverterInputDigest,
    InstrumentCodeMapping,
    QlibSemanticSample,
    QlibViewFile,
    QlibViewManifest,
    QlibViewSpec,
)
from quantos.contracts.refs import ArtifactRef, DataSnapshotRef
from quantos.contracts.research import (
    ExperimentAuthoringSpec,
    ExpressionAuthoringSpec,
    HardGateId,
    ResearchPolicy,
    ResearchSegment,
    ResolvedExperimentSpec,
    ResolvedStrategySpec,
    SoftGateThreshold,
    SoftMetric,
    StrategyAuthoringSpec,
    ThresholdComparison,
    ValidationPolicy,
    ValidationSubperiod,
)
from quantos.contracts.research_execution import (
    HistoricalUniverseMember,
    HistoricalUniverseResolution,
    PITAuditEvidenceBundle,
    PITAuditEvidenceCollection,
    PITAuditEvidenceItem,
    QlibExpressionTranslation,
)
from quantos.contracts.signal import (
    SignalArtifactFile,
    SignalArtifactManifest,
    SignalInputHash,
    SignalRow,
)
from quantos.contracts.snapshot import (
    ColumnManifest,
    DataQualityPolicy,
    DataQualityReport,
    DataQualityRule,
    DataSnapshotManifest,
    QualityGateResult,
    SnapshotBuildSpec,
    SnapshotDiff,
    SnapshotFileManifest,
    SnapshotSourceKind,
)
from quantos.contracts.status import ReasonCode, RunStatus, StrategyStatus, ValidationVerdict
from quantos.contracts.temporal import (
    AvailabilityEvidenceLevel,
    DecisionSchedule,
    TemporalMetadata,
    TemporalPolicyError,
)
from quantos.contracts.validation import (
    GateResult,
    GateSeverity,
    ReproducibilityComparison,
    RobustnessCaseResult,
    RobustnessKind,
    ValidationArtifactFile,
    ValidationGateId,
    ValidationMetric,
    ValidationReport,
)

__all__ = [
    "ArtifactRef",
    "AvailabilityEvidenceLevel",
    "BacktestArtifactFile",
    "BacktestArtifactManifest",
    "BacktestInputHash",
    "BacktestPolicy",
    "BacktestReconciliation",
    "BacktestReconciliationCheck",
    "CanonicalContract",
    "CanonicalPITAuditRequest",
    "CanonicalizationError",
    "CodeProvenance",
    "ColumnManifest",
    "ConverterInputDigest",
    "CostPolicy",
    "DataQualityPolicy",
    "DataQualityReport",
    "DataQualityRule",
    "DataSnapshotManifest",
    "DataSnapshotRef",
    "DecisionSchedule",
    "EventType",
    "ExperimentAuthoringSpec",
    "ExpressionAuthoringSpec",
    "GateResult",
    "GateSeverity",
    "HardGateId",
    "HistoricalUniverseMember",
    "HistoricalUniverseResolution",
    "ImmutableEvent",
    "InstrumentCodeMapping",
    "LineageSource",
    "MembershipUse",
    "OperatorDelayPolicy",
    "PITAuditEvidenceBundle",
    "PITAuditEvidenceCollection",
    "PITAuditEvidenceItem",
    "PITAuditReport",
    "PITAuditSpec",
    "PITEvidenceMode",
    "PITGateId",
    "PITGateResult",
    "QlibBacktestConfig",
    "QlibExpressionTranslation",
    "QlibSemanticSample",
    "QlibViewFile",
    "QlibViewManifest",
    "QlibViewSpec",
    "QualityGateResult",
    "ReasonCode",
    "ReproducibilityComparison",
    "ResearchPolicy",
    "ResearchSegment",
    "ResolvedExperimentSpec",
    "ResolvedStrategySpec",
    "RobustnessCaseResult",
    "RobustnessKind",
    "RunStatus",
    "RuntimeFingerprint",
    "RuntimePackageVersion",
    "SafeExpressionNode",
    "SafeQlibExpressionSpec",
    "SafeQlibOperator",
    "SignalArtifactFile",
    "SignalArtifactManifest",
    "SignalInputHash",
    "SignalRow",
    "SnapshotBuildSpec",
    "SnapshotDiff",
    "SnapshotFileManifest",
    "SnapshotSourceKind",
    "SoftGateThreshold",
    "SoftMetric",
    "StrategyAuthoringSpec",
    "StrategyStatus",
    "TemporalMetadata",
    "TemporalPolicyError",
    "ThresholdComparison",
    "TransformLineage",
    "ValidationArtifactFile",
    "ValidationGateId",
    "ValidationMetric",
    "ValidationPolicy",
    "ValidationReport",
    "ValidationSubperiod",
    "ValidationVerdict",
    "canonical_json_bytes",
    "sha256_bytes",
]
