"""Run, validation, and strategy lifecycle states."""

from enum import StrEnum


class RunStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ValidationVerdict(StrEnum):
    PASS = "PASS"
    REJECT = "REJECT"
    NOT_EVALUATED = "NOT_EVALUATED"


class StrategyStatus(StrEnum):
    DRAFT = "DRAFT"
    CANDIDATE = "CANDIDATE"
    VALIDATING = "VALIDATING"
    REJECTED = "REJECTED"
    VALIDATED = "VALIDATED"


class ReasonCode(StrEnum):
    ADMISSION_REJECTED = "ADMISSION_REJECTED"
    AUTHORITY_FIELD_DENIED = "AUTHORITY_FIELD_DENIED"
    AUTHORITY_ROOT_INVALID = "AUTHORITY_ROOT_INVALID"
    CAPABILITY_DENIED = "CAPABILITY_DENIED"
    CAMPAIGN_CLOSED = "CAMPAIGN_CLOSED"
    CONTAMINATION_REQUIRED = "CONTAMINATION_REQUIRED"
    EVENT_CHAIN_INVALID = "EVENT_CHAIN_INVALID"
    HARNESS_CAPABILITY_MISSING = "HARNESS_CAPABILITY_MISSING"
    HARNESS_EXECUTION_FAILED = "HARNESS_EXECUTION_FAILED"
    HARNESS_TRANSCRIPT_INVALID = "HARNESS_TRANSCRIPT_INVALID"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    SNAPSHOT_HASH_MISMATCH = "SNAPSHOT_HASH_MISMATCH"
    SOURCE_INCOMPLETE = "SOURCE_INCOMPLETE"
    LOOK_AHEAD = "LOOK_AHEAD"
    MODEL_CONFIGURATION_MISMATCH = "MODEL_CONFIGURATION_MISMATCH"
    UNKNOWN_AVAILABILITY = "UNKNOWN_AVAILABILITY"
    QLIB_EXECUTION_FAILED = "QLIB_EXECUTION_FAILED"
    OOS_POLICY_VIOLATION = "OOS_POLICY_VIOLATION"
    OOS_ALREADY_ACCESSED = "OOS_ALREADY_ACCESSED"
    PATH_BOUNDARY_VIOLATION = "PATH_BOUNDARY_VIOLATION"
    REPRODUCIBILITY_MISMATCH = "REPRODUCIBILITY_MISMATCH"
    RESEARCH_BUDGET_EXCEEDED = "RESEARCH_BUDGET_EXCEEDED"
    SOFT_THRESHOLD_NOT_MET = "SOFT_THRESHOLD_NOT_MET"
    ARTIFACT_CORRUPTED = "ARTIFACT_CORRUPTED"
    DUPLICATE_ID_CONFLICT = "DUPLICATE_ID_CONFLICT"
    STATE_TRANSITION_INVALID = "STATE_TRANSITION_INVALID"
    RESOURCE_BUDGET_EXCEEDED = "RESOURCE_BUDGET_EXCEEDED"
    SECRET_ACCESS_DENIED = "SECRET_ACCESS_DENIED"
