"""Run, validation, and strategy lifecycle states."""

from enum import StrEnum


class RunStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class ValidationVerdict(StrEnum):
    PASS = "PASS"
    REJECT = "REJECT"
    NOT_EVALUATED = "NOT_EVALUATED"


class StrategyStatus(StrEnum):
    DRAFT = "DRAFT"
    CANDIDATE = "CANDIDATE"
    VALIDATING = "VALIDATING"
    REJECTED = "REJECTED"
    VALIDATED = "VALIDATED"


class ReasonCode(StrEnum):
    SCHEMA_INVALID = "SCHEMA_INVALID"
    SNAPSHOT_HASH_MISMATCH = "SNAPSHOT_HASH_MISMATCH"
    SOURCE_INCOMPLETE = "SOURCE_INCOMPLETE"
    LOOK_AHEAD = "LOOK_AHEAD"
    UNKNOWN_AVAILABILITY = "UNKNOWN_AVAILABILITY"
    QLIB_EXECUTION_FAILED = "QLIB_EXECUTION_FAILED"
    OOS_POLICY_VIOLATION = "OOS_POLICY_VIOLATION"
    REPRODUCIBILITY_MISMATCH = "REPRODUCIBILITY_MISMATCH"
    SOFT_THRESHOLD_NOT_MET = "SOFT_THRESHOLD_NOT_MET"
    ARTIFACT_CORRUPTED = "ARTIFACT_CORRUPTED"
